<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
					</button>
					<h1>
						<a class="navbar-brand" href="./"><img class="navbar-brand" src="images/logo.png" alt="Pokémon"><?php echo $parentTitle;?></a>
					</h1>
				</div>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="gen_1-2.php">I-II</a></li>
						<li><a href="gen_3-4.php">III-IV</a></li>
						<li><a href="gen_5-7.php">V-VII</a></li>
						<li><a href="colophon.php">Colophon</a></li>
					</ul>
				</div>
			</div>
		</nav>
