<div id="main-container" class="col-xs-12">
	
		<div id="tiles-container" class="sampleClass">
				
			<div class="tl-page" data-tl-template="tempA">
				
				<div id="tileD">
					<h2>Generation I-II</h2>
					<span class="content-hidden">
						<p>Take a look at Generations I and II</p>
					</span>
				</div>
				<div id="tileE">
					<h2>Generations III-IV</h2>
					<span class="content-hidden content-hidden-small">
						<p>
							aaa
						</p>
					</span>
				</div>
				
				<div id="tileH">
					<h2>Generation V-VII</h2>
					<span class="content-hidden"><p>To check some stuff on Generations V-VII</p>
					</span>
				</div>
				<div id="tileI">
					<h2>Colophon</h2>
					<span class="content-hidden">
						<p><a href="colophon.php">Some of our responsibilities include....</a></p>
						
					</span>
				</div>
				<div id="tileJ"></div>
				
			</div> 
			
			
	
		</div>
				
	</div>

	
	
